galaxy_info:
  role_name: app
  author: ail-13
  namespace: infra
  description: Устанавливает Docker на сервер и запускает приложение в контейнере

  license: All Rights Reserved

  min_ansible_version: "2.10"

dependencies: []
