- name: Создаем каталог для данных
  ansible.builtin.file:
    path: "{{ mongodb_data_path }}/backup"
    state: directory
    group: mongodb
    owner: mongodb

- name: Переносим приложение
  ansible.builtin.copy:
    src: files/
    dest: "/home/{{ vm_username }}/backup/"
    group: "{{ vm_username }}"
    owner: "{{ vm_username }}"
    mode: "644"
    directory_mode: "755"

- name: Переносим переменные окружения для приложения
  ansible.builtin.template:
    src: templates/.env.j2
    dest: "/home/{{ vm_username }}/backup/.env"
    group: "{{ vm_username }}"
    owner: "{{ vm_username }}"
    mode: "644"

- name: Считываем UID пользователя
  ansible.builtin.getent:
    database: passwd
    key: "{{ vm_username }}"

- name: Переносим docker-compose.yml на сервер
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "/home/{{ vm_username }}/backup/docker-compose.yml"
    group: "{{ vm_username }}"
    owner: "{{ vm_username }}"
    mode: "644"

# - name: Запуск Docker Compose
#   community.general.docker_compose:
#     project_src: "/home/{{ vm_username }}/backup"
#     env_file: .env
#     state: present
#     build: true