---
- name: Настраиваем подключение pbm-agent к MongoDB
  ansible.builtin.copy:
    content: 'PBM_MONGODB_URI="mongodb://{{ mongodb_backup_name }}:localhost:{{ mongodb_port }}/?authSource=admin"'
    dest: /etc/default/pbm-agent
  no_log: true
  register: pbm_agent_config_result

- name: Перезапускаем pbm-agent
  become: true
  ansible.builtin.service:
    name: pbm-agent
    state: restarted
  when: pbm_agent_config_result.changed

- name: Проверяем что pbm-agent запущен
  ansible.builtin.service:
    name: pbm-agent
    state: started
    enabled: true
