db:
    name: ENC[AES256_GCM,data:OYH8fg==,iv:faS4Ts9GfrOlXHO4IV6iwVaP/xMKRzYxDpiDlNIQVT0=,tag:paLNKPit6oU8TZp0/qR1tw==,type:str]
    user: ENC[AES256_GCM,data:36CJsAfL,iv:le5fy4EETJlKe0Z64BJUCSEeJdmRahg992/bbrrzAVg=,tag:YDiv4jIw5MSBVHuJXBOKvA==,type:str]
    password: ENC[AES256_GCM,data:VOF673Uep8Duow==,iv:P9Rcjn/5QCK/n8IXQxQ3VyHQq1HzcTDGsl2PpYHL0GQ=,tag:V/I9Jl125C9HnVrzB3cVYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-15T14:52:10Z"
    mac: ENC[AES256_GCM,data:Emt4v3vNtJNc0fs8Z2tTRyZGzzoSPxoMKsbL8MkBBcK1dSxuM36YHGQ3MWu4+iEjMhgPxGNyLOcl/zkMQbjbAIa+Sf5s6gcvraqBRA7881QFpbbfW9afhQIPJ8FNsnVtnAkrUxd9/p2RvmahoqplC1TYQtNjo3TCf8MPWheFxII=,iv:lTCxVgetlF+UEh6DkUPR0Y6/y1LAZKYXQjlbH0dQYw8=,tag:+PqfvI05SGeWa4Kqc0/9fA==,type:str]
    pgp:
        - created_at: "2024-02-15T14:47:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA3iaB4Kr9VdUAQv5AZ49iTpwFK9u1LtN1sg2GCTH/YPKXtHviKQj9BEyyz8+
            6DlXHSBHBhLCq/20knKQRu3eNsfaQfVmguogWabtB3JX/0ErAzPTPu/Xpa9IS4Rn
            rlNDmLUhbmaqxA0TCqCBH0m7OfpYB9npaw3FScYFgHDwivwEwa3v0j+eMFTq6CRI
            OdaxTX2BPDYqsiEvmvVrf6+kscAOFLTNEcZ0y4w0NoYrBSfRiJ/yXLQvwRlRZFgp
            fYaO7BUAuWtsOvKlnd+RwA8YwtpCNqqXvSUFmWAdF2gYgUmVI1n5YKfCdls+Hk1a
            nJus5PsDCM7plnwyCTBhd5FR9kKjctUMtqTX+Le9p038H0jlSimUGfWw6Ad2sLpa
            Kx3SdcHGRMXvqelIOEfKRVr4GJsN4LRTRwppUu4YiyP+TwVsfJY3r541Tk7MfE3c
            ex1XXn2zyhtxxvwY8FIk+eNaeRpF8pGYGGQE9noY6N2AGLWQT2t7trA5emkWuA9R
            SuwOvLtrpldkuzYK7Ey80l4BVzEhj1faP/CvxOT1pyHQr+S6fqINFkcqrnmOTVux
            3eOBpo4l5sahAozvYyhDxr1rB8QSCViKdTWb7kd9Rdp4TmFwTk0ArTpOa50IGlwj
            p/8v0LUave4D+ArTrTB/
            =v67C
            -----END PGP MESSAGE-----
          fp: 43B1904EDFCF5596E096382A1E5122860BD8DE24
    unencrypted_suffix: _unencrypted
    version: 3.8.1
