app:
  deployment:
    name: myapp
    replicas: 1
    label: app
  port: 80
  image:
    repository: antonlarichev/short-app
    tag: v1.4
  resources:
    limits:
      memory: "128Mi"
      cpu: "100m"
api:
  deployment:
    name: myapi
    replicas: 1
    label: api
  port: 3000
  image:
    repository: antonlarichev/short-api
    tag: v1.0
  resources:
    limits:
      memory: "512Mi"
      cpu: "200m"
  envs:
    - DATABASE_URL
postgres:
  deployment:
    name: postgres
    label: db
  port: 5432
  image:
    repository: postgres
    tag: 16.0
  resources:
    limits:
      memory: "256Mi"
      cpu: "100m"
  envs:
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
