---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: yamllint
platforms:
  - name: instance1
    box: ubuntu/focal64
    config_options:
      vm.boot_timeout: 1800
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
      # создаем дополнительный диск
      - "customize ['createmedium', 'disk', '--filename', 'molecule_additional_disk1', '--size', '2048']"
      - "customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', '2', '--type', 'hdd', '--medium', 'molecule_additional_disk1.vdi']"
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: 192.168.56.10
        type: static
  - name: instance2
    box: ubuntu/focal64
    config_options:
      vm.boot_timeout: 1800
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
      # создаем дополнительный диск
      - "customize ['createmedium', 'disk', '--filename', 'molecule_additional_disk2', '--size', '2048']"
      - "customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', '2', '--type', 'hdd', '--medium', 'molecule_additional_disk2.vdi']"
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: 192.168.56.20
        type: static
  - name: instance3
    box: ubuntu/focal64
    config_options:
      vm.boot_timeout: 1800
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
      # создаем дополнительный диск
      - "customize ['createmedium', 'disk', '--filename', 'molecule_additional_disk3', '--size', '2048']"
      - "customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', '2', '--type', 'hdd', '--medium', 'molecule_additional_disk3.vdi']"
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: 192.168.56.30
        type: static

provisioner:
  name: ansible
  ansible_user: vagrant
  inventory:
    links:
      group_vars: group_vars
      hosts: inventory.yml
  lint:
    name: ansible-lint
# scenario:
#   name: default
verifier:
  name: testinfra