---
- name: Устанавливаем необходимые пакеты
  hosts: all
  gather_facts: false
  roles:
    - role: preconfig

- name: Настраиваем сервера под MongoDB
  hosts: db
  roles:
    - role: mongodb

- name: Настраиваем сервера под приложение
  hosts: app
  gather_facts: false
  roles:
    - role: app

- name: Настраиваем сервер мониторинга
  hosts: monitoring
  roles:
    - role: monitoring
    
- name: Подключаем сервера с MongoDB к мониторингу
  hosts: db
  roles:
    - role: pmm_client

- name: Подключаем сервера с приложением к мониторингу
  hosts: app
  roles:
    - role: pmm_client
