---
- name: DockerInstall
  hosts: db
  become: true

  tasks:
    - name: Установка дополнительных пакетов
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - ca-certificates
          - curl
          - gnupg

    - name: Добавляем ключ Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /usr/share/keyrings/docker.gpg

    - name: Добавление репозитория Docker
      ansible.builtin.apt_repository:
        update_cache: true
        repo: deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker

    - name: Установка Docker
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-compose

    - name: Проверяем что группа docker существует
      ansible.builtin.group:
        name: docker
        state: present

    - name: "Добавление пользователя к группе docker"
      ansible.builtin.user:
        name: "{{ vm_username }}"
        groups: docker
        append: true

    - name: Сбрасываем подключение чтобы обновились доступы пользователя
      ansible.builtin.meta:
        reset_connection

    - name: Проверяем что Docker запущен
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

- name: DiveInstall
  hosts: db
  become: true

  tasks:
    - name: Установка dive
      block:
        - name: Проверяем последнюю версию dive
          ansible.builtin.uri:
            url: https://api.github.com/repos/wagoodman/dive/releases/latest
            body_format: json
          register: dive
          failed_when: dive.failed

        - name: Устанавливаем dive последней версии
          ansible.builtin.apt:
            deb: https://github.com/wagoodman/dive/releases/download/{{ dive.json.tag_name }}/dive_{{ dive.json.tag_name | replace('v', '') }}_linux_amd64.deb
            state: present
          register: dive
      rescue:
        - name: Ошибка установки dive
          ansible.builtin.debug:
            msg: Не удалось установить dive
