---
- name: MongoInstall
  hosts: all
  become: true

  tasks:
    - name: Добавляем ключ MongoDB
      ansible.builtin.apt_key:
        url: https://pgp.mongodb.com/server-7.0.asc
        state: present
        keyring: /usr/share/keyrings/mongodb-server-7.0.gpg

    - name: Добавление репозитория Docker
      ansible.builtin.apt_repository:
        update_cache: true
        repo: deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse
        state: present
        filename: mongodb-org-7.0

    - name: Установка MongoDB
      ansible.builtin.apt:
        update_cache: true
        state: present
        name: mongodb-org

    - name: Проверяем что MongoDB запущена
      ansible.builtin.service:
        name: mongod
        enabled: true
