---
- name: Конфигурирование диска для хранения БД
  import_playbook: diskPrepare.yml

- name: Установка Docker и dive
  import_playbook: dockerInstall.yml

- name: Развертывание базы данных и приложения
  import_playbook: deploy.yml
