apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.deployment.name }}-secret
type: Opaque
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-cluster-ip:%d/%s"
  .Values.db.user
  .Values.db.password
  .Values.postgres.deployment.name
  (.Values.postgres.port | int64)
  .Values.db.name | b64enc | quote }}
