apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.deployment.name }}-pvc
spec:
  # storageClassName: fast.ru-1c
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
