apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.deployment.name }}-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.db.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc }}
  POSTGRES_DB: {{ .Values.db.name | b64enc }}
