apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.deployment.name }}-cluster-ip
spec:
  type: ClusterIP
  selector:
    components: {{ .Values.postgres.deployment.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}