---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
  options:
    boot_timeout: 1800
lint: yamllint
platforms:
  - name: instance
    box: ubuntu/focal64
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
provisioner:
  name: ansible
  ansible_user: vagrant
  lint:
    name: ansible-lint
# scenario:
#   name: default
verifier:
  name: testinfra