- name: Перезапускаем MongoDB
  become: true
  ansible.builtin.service:
    name: mongod
    state: restarted

- name: Перезапускаем pbm-agent
  become: true
  ansible.builtin.service:
    name: pbm-agent
    state: restarted
