apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    components: app
spec:
  containers:
    - name: app
      image: antonlarichev/short-app:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
