galaxy_info:
  role_name: preconfig
  author: ail-13
  namespace: infra
  description: Устанавливает несколько сервисов для работы на сервере

  license: All Rights Reserved

  min_ansible_version: "2.4"

dependencies: []
