galaxy_info:
  role_name: mongodb
  author: ail-13
  description: Устанавливает Docker на сервер и запускает MongoDB в контейнере

  license: All Rights Reserved

  min_ansible_version: "2.10"

dependencies: []
