---
- name: Установка dive
  block:
    - name: Проверяем последнюю версию dive
      ansible.builtin.uri:
        url: https://api.github.com/repos/wagoodman/dive/releases/latest
        body_format: json
      register: dive
      when: dive_version == "latest"

    - name: Обновляем dive_version на полученное значение из JSON, если dive_version было "latest"
      ansible.builtin.set_fact:
        dive_version: "{{ dive.json.tag_name | replace('v', '') }}"
      when: dive_version == "latest"

    - name: Устанавливаем dive нужной версии
      become: true
      ansible.builtin.apt:
        deb: https://github.com/wagoodman/dive/releases/download/v{{ dive_version }}/dive_{{ dive_version }}_linux_{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}.deb
        state: present

  rescue:
    - name: Ошибка установки dive
      ansible.builtin.fail:
        msg: Не удалось установить dive
      failed_when: false
