---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: yamllint
platforms:
  - name: instance
    box: ubuntu/focal64
    config_options:
      vm.boot_timeout: 1800
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
provisioner:
  name: ansible
  ansible_user: vagrant
  inventory:
    group_vars:
      all:
        vm_username: vagrant
        app_db_username: root
        app_db_pass: mongo123
        app_db_host: 111.111.111.111
        app_path: files/app/
  lint:
    name: ansible-lint
# scenario:
#   name: default
verifier:
  name: testinfra