---
- block:
  - name: Задаем пароль для администратора
    community.docker.docker_container_exec:
      container: pmm-server
      command: "change-admin-password {{ monitoring_password }}"
    register: docker_exec_result
    until: docker_exec_result.rc == 0
    retries: 30
    delay: 5
    when: docker_compose_result is defined and docker_compose_result.changed or monitoring_percona_force_config == true or monitoring_percona_force_config == 'true'
    failed_when: docker_exec_result.rc != 0

  rescue:
    - fail:
        msg: "Ошибка при установке пароля pmm: {{ docker_exec_result.stdout_lines[-1] }}"
