---
- block:
  - name: Регистрируемся на сервере PMM
    ansible.builtin.command:
      cmd: pmm-admin config --server-insecure-tls --server-url=https://admin:{{ monitoring_password }}@{{ monitoring_ip }}:443
    register: pmm_config_result

  rescue:
    - fail:
        msg: "Ошибка при регистрации на сервере PMM: {{ pmm_config_result }}"
      when: pmm_config_result is not defined or pmm_config_result.stdout_lines is not defined
    - fail:
        msg: "Ошибка при регистрации на сервере PMM: {{ pmm_config_result.stdout_lines[-1] }}"
      when: pmm_config_result is defined and pmm_config_result.stdout_lines is defined and not (pmm_config_result.stdout_lines | default([]) | regex_search('Node with name .* already exists.'))

- block:
  - name: Регистрируем сервис MongoDB на сервере PMM
    ansible.builtin.command:
      cmd: pmm-admin add mongodb --username={{ mongodb_percona_name }} --password={{ mongodb_percona_pass }} --replication-set {{ mongodb_rs_name }} --cluster cluster_{{ mongodb_rs_name }} mongodb({{ ansible_hostname }}) 127.0.0.1:{{ mongodb_port }}
    when: mongodb_percona_name is defined
    register: mongo_config_result

  rescue:
    - fail:
        msg: "Ошибка при регистрации сервиса MongoDB на сервере PMM: {{ mongo_config_result }}"
      when: mongo_config_result is not defined or mongo_config_result.stdout_lines is not defined
    - fail:
        msg: "Ошибка при регистрации на сервере PMM: {{ mongo_config_result.stdout_lines[-1] }}"
      when: mongo_config_result is defined and mongo_config_result.stdout_lines is defined and not (mongo_config_result.stdout_lines | default([]) | regex_search('Service with name .* already exists.'))